// <auto-generated />
using System;
using BP_Diary_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BP_Diary_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BP_Diary_1.Models.bp_diary", b =>
                {
                    b.Property<int>("bp_diary_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("date_record")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("diastolic")
                        .HasColumnType("integer");

                    b.Property<int>("systolic")
                        .HasColumnType("integer");

                    b.ToTable("bp_diary");
                });
#pragma warning restore 612, 618
        }
    }
}
